// ==============================================
// DevForge — Bash Script Generator Utils
// ==============================================
// Generate production-grade Bash scripts with
// strict error handling (set -euo pipefail), ANSI
// color logging helpers, trap cleanup handlers,
// CLI argument flags parser, and custom script bodies.
// ==============================================

export interface BashScriptConfig {
  scriptName: string;
  description: string;
  shebang: '#!/usr/bin/env bash' | '#!/bin/bash';
  strictMode: boolean; // set -euo pipefail
  includeColors: boolean;
  includeLoggers: boolean;
  includeTrap: boolean;
  trapCleanupCommand: string;
  includeArgParser: boolean;
  arguments: {
    name: string;
    flag: string;
    description: string;
    defaultValue: string;
  }[];
  customBody: string;
}

export interface BashScriptValidationResult {
  isValid: boolean;
  errors: string[];
}

/**
 * Generates formatted, production-grade Bash script content.
 */
export function generateBashScript(config: BashScriptConfig): string {
  const lines: string[] = [];

  // Shebang & header
  lines.push(config.shebang);
  lines.push('');
  lines.push('# ==============================================');
  lines.push(`# Script Name : ${config.scriptName || 'script.sh'}`);
  lines.push(`# Description : ${config.description || 'Automated Bash Script'}`);
  lines.push('# Generated by DevForge Developer Studio');
  lines.push('# ==============================================');
  lines.push('');

  // Strict mode
  if (config.strictMode) {
    lines.push('# Enable strict error handling (exit on error, unset var, or pipeline failure)');
    lines.push('set -euo pipefail');
    lines.push('IFS=$\'\\n\\t\'');
    lines.push('');
  }

  // Color constants
  if (config.includeColors) {
    lines.push('# Terminal ANSI Color Definitions');
    lines.push('readonly COLOR_RESET="\\033[0m"');
    lines.push('readonly COLOR_INFO="\\033[1;34m"');
    lines.push('readonly COLOR_SUCCESS="\\033[1;32m"');
    lines.push('readonly COLOR_WARN="\\033[1;33m"');
    lines.push('readonly COLOR_ERROR="\\033[1;31m"');
    lines.push('');
  }

  // Logger functions
  if (config.includeLoggers) {
    lines.push('# Logging Helpers');
    if (config.includeColors) {
      lines.push('log_info() { echo -e "${COLOR_INFO}[INFO]${COLOR_RESET} $(date \'+%Y-%m-%d %H:%M:%S\') - $*"; }');
      lines.push('log_success() { echo -e "${COLOR_SUCCESS}[SUCCESS]${COLOR_RESET} $(date \'+%Y-%m-%d %H:%M:%S\') - $*"; }');
      lines.push('log_warn() { echo -e "${COLOR_WARN}[WARN]${COLOR_RESET} $(date \'+%Y-%m-%d %H:%M:%S\') - $*" >&2; }');
      lines.push('log_error() { echo -e "${COLOR_ERROR}[ERROR]${COLOR_RESET} $(date \'+%Y-%m-%d %H:%M:%S\') - $*" >&2; }');
    } else {
      lines.push('log_info() { echo "[INFO] $(date \'+%Y-%m-%d %H:%M:%S\') - $*"; }');
      lines.push('log_success() { echo "[SUCCESS] $(date \'+%Y-%m-%d %H:%M:%S\') - $*"; }');
      lines.push('log_warn() { echo "[WARN] $(date \'+%Y-%m-%d %H:%M:%S\') - $*" >&2; }');
      lines.push('log_error() { echo "[ERROR] $(date \'+%Y-%m-%d %H:%M:%S\') - $*" >&2; }');
    }
    lines.push('');
  }

  // Trap handler
  if (config.includeTrap) {
    lines.push('# Exit cleanup trap');
    lines.push('cleanup() {');
    lines.push('  local exit_code=$?');
    if (config.trapCleanupCommand.trim()) {
      lines.push(`  ${config.trapCleanupCommand.trim()}`);
    } else {
      lines.push('  # Perform temporary file cleanup here');
    }
    lines.push('  if [[ ${exit_code} -ne 0 ]]; then');
    if (config.includeLoggers) {
      lines.push('    log_error "Script exited abnormally with code ${exit_code}"');
    } else {
      lines.push('    echo "[ERROR] Script exited abnormally with code ${exit_code}" >&2');
    }
    lines.push('  fi');
    lines.push('}');
    lines.push('trap cleanup EXIT INT TERM');
    lines.push('');
  }

  // Argument parser
  if (config.includeArgParser && config.arguments.length > 0) {
    lines.push('# Default argument values');
    config.arguments.forEach((arg) => {
      lines.push(`${arg.name.toUpperCase()}="${arg.defaultValue}"`);
    });
    lines.push('');
    lines.push('show_help() {');
    lines.push(`  echo "Usage: $0 [OPTIONS]"`);
    config.arguments.forEach((arg) => {
      lines.push(`  echo "  ${arg.flag.padEnd(16)} ${arg.description} (default: ${arg.defaultValue})"`);
    });
    lines.push('  echo "  -h, --help       Show this help message and exit"');
    lines.push('}');
    lines.push('');
    lines.push('# CLI Argument Parsing Loop');
    lines.push('while [[ $# -gt 0 ]]; do');
    lines.push('  case "$1" in');
    config.arguments.forEach((arg) => {
      lines.push(`    ${arg.flag})`);
      lines.push(`      ${arg.name.toUpperCase()}="$2"`);
      lines.push('      shift 2');
      lines.push('      ;;');
    });
    lines.push('    -h|--help)');
    lines.push('      show_help');
    lines.push('      exit 0');
    lines.push('      ;;');
    lines.push('    *)');
    if (config.includeLoggers) {
      lines.push('      log_error "Unknown option: $1"');
    } else {
      lines.push('      echo "Unknown option: $1" >&2');
    }
    lines.push('      show_help');
    lines.push('      exit 1');
    lines.push('      ;;');
    lines.push('  esac');
    lines.push('done');
    lines.push('');
  }

  // Main Script Execution Body
  lines.push('# ==============================================');
  lines.push('# Main Script Logic');
  lines.push('# ==============================================');
  lines.push('main() {');
  const bodyLines = config.customBody.trim().split('\n');
  bodyLines.forEach((bl) => {
    lines.push(`  ${bl}`);
  });
  lines.push('}');
  lines.push('');
  lines.push('main "$@"');

  return lines.join('\n').trim();
}

/**
 * Validates Bash script generator configuration.
 */
export function validateBashScriptConfig(
  config: BashScriptConfig
): BashScriptValidationResult {
  const errors: string[] = [];

  if (!config.scriptName.trim()) {
    errors.push('Script Name is required.');
  }

  return {
    isValid: errors.length === 0,
    errors,
  };
}

export const BASH_PRESETS: {
  name: string;
  description: string;
  config: BashScriptConfig;
}[] = [
  {
    name: 'Production Deployment Boilerplate',
    description: 'Zero-downtime app deployment script with strict mode, logging, trap cleanup, and CLI flag options',
    config: {
      scriptName: 'deploy.sh',
      description: 'Production Application Zero-Downtime Deployment Script',
      shebang: '#!/usr/bin/env bash',
      strictMode: true,
      includeColors: true,
      includeLoggers: true,
      includeTrap: true,
      trapCleanupCommand: 'rm -rf /tmp/deploy-staging.*',
      includeArgParser: true,
      arguments: [
        {
          name: 'environment',
          flag: '--env',
          description: 'Target deployment environment (staging/production)',
          defaultValue: 'production',
        },
        {
          name: 'branch',
          flag: '--branch',
          description: 'Git release branch or tag to deploy',
          defaultValue: 'main',
        },
      ],
      customBody: [
        'log_info "Starting deployment for environment: ${ENVIRONMENT} (branch: ${BRANCH})"',
        '# Step 1: Pull latest changes',
        'git fetch --all --tags --prune',
        'git checkout "${BRANCH}" && git pull origin "${BRANCH}"',
        '',
        '# Step 2: Install dependencies & build project',
        'log_info "Building production package..."',
        'pnpm install --frozen-lockfile',
        'pnpm build',
        '',
        '# Step 3: Restart app service',
        'log_success "Deployment completed successfully!"',
      ].join('\n'),
    },
  },
  {
    name: 'Automated Database Backup Script',
    description: 'PostgreSQL backup pipeline with gzip compression, retention cleanup, and alert logs',
    config: {
      scriptName: 'db-backup.sh',
      description: 'Automated PostgreSQL Database Dump and Compression Script',
      shebang: '#!/usr/bin/env bash',
      strictMode: true,
      includeColors: true,
      includeLoggers: true,
      includeTrap: true,
      trapCleanupCommand: 'rm -f /tmp/db-dump.sql',
      includeArgParser: false,
      arguments: [],
      customBody: [
        'readonly BACKUP_DIR="/var/backups/postgres"',
        'readonly TIMESTAMP="$(date +%Y%m%d_%H%M%S)"',
        'readonly ARCHIVE_FILE="${BACKUP_DIR}/db_backup_${TIMESTAMP}.sql.gz"',
        '',
        'mkdir -p "${BACKUP_DIR}"',
        'log_info "Creating PostgreSQL database dump..."',
        'pg_dump -U postgres app_db | gzip > "${ARCHIVE_FILE}"',
        '',
        'log_success "Backup saved to: ${ARCHIVE_FILE}"',
        '# Prune backups older than 14 days',
        'find "${BACKUP_DIR}" -name "db_backup_*.sql.gz" -mtime +14 -delete',
      ].join('\n'),
    },
  },
  {
    name: 'Health Check & Service Watchdog',
    description: 'Monitors endpoint HTTP status code and auto-restarts service if unresponsive',
    config: {
      scriptName: 'health-watchdog.sh',
      description: 'HTTP Service Health Watchdog & Auto-Recovery Script',
      shebang: '#!/usr/bin/env bash',
      strictMode: true,
      includeColors: true,
      includeLoggers: true,
      includeTrap: false,
      trapCleanupCommand: '',
      includeArgParser: false,
      arguments: [],
      customBody: [
        'readonly TARGET_URL="http://127.0.0.1:3000/api/health"',
        'readonly STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" "${TARGET_URL}" || echo "000")',
        '',
        'if [[ "${STATUS_CODE}" == "200" ]]; then',
        '  log_info "Service is healthy (HTTP ${STATUS_CODE})"',
        '  exit 0',
        'else',
        '  log_error "Service check failed (HTTP ${STATUS_CODE}). Triggering restart..."',
        '  systemctl restart devforge-app.service',
        'fi',
      ].join('\n'),
    },
  },
];
