// ==============================================
// DevForge — .gitattributes Generator Utilities
// ==============================================
// Generate standardized .gitconfig/.gitattributes
// line ending normalization (LF/CRLF), Git LFS
// large file tracking rules, and GitHub Linguist flags.
// ==============================================

export interface GitAttributeRule {
  id: string;
  pattern: string; // e.g. '*.png', '*', 'dist/*'
  attributes: string; // e.g. 'filter=lfs diff=lfs merge=lfs -text'
  comment?: string;
}

export interface GitAttributesConfig {
  defaultLineEnding: 'lf' | 'crlf' | 'auto' | 'none';
  enableLfsRules: boolean;
  lfsExtensions: string[]; // e.g. ['png', 'jpg', 'psd', 'mp4', 'zip']
  customRules: GitAttributeRule[];
}

export interface GitAttributesValidationResult {
  isValid: boolean;
  errors: string[];
  warnings: string[];
}

let attrCounter = 1;
export function generateGitAttributeRuleId(): string {
  return `attr_${Date.now()}_${attrCounter++}`;
}

/**
 * Generates .gitattributes file output based on config.
 */
export function generateGitAttributesContent(config: GitAttributesConfig): string {
  const lines: string[] = [];
  lines.push('# .gitattributes generated by DevForge');
  lines.push('');

  // Line ending normalization
  if (config.defaultLineEnding !== 'none') {
    lines.push('# Default line ending behavior');
    if (config.defaultLineEnding === 'auto') {
      lines.push('* text=auto');
    } else {
      lines.push(`* text=auto eol=${config.defaultLineEnding}`);
    }
    lines.push('');
  }

  // Git LFS
  if (config.enableLfsRules && config.lfsExtensions.length > 0) {
    lines.push('# Git LFS (Large File Storage) tracking');
    config.lfsExtensions.forEach((ext) => {
      const normalizedExt = ext.startsWith('.') ? ext.slice(1) : ext;
      lines.push(
        `*.${normalizedExt} filter=lfs diff=lfs merge=lfs -text`
      );
    });
    lines.push('');
  }

  // Custom & Linguist Rules
  if (config.customRules.length > 0) {
    lines.push('# Custom attributes & GitHub Linguist overrides');
    config.customRules.forEach((rule) => {
      if (rule.comment) {
        lines.push(`# ${rule.comment}`);
      }
      lines.push(`${rule.pattern} ${rule.attributes}`);
    });
    lines.push('');
  }

  return lines.join('\n').trim();
}

/**
 * Validates .gitattributes configuration.
 */
export function validateGitAttributesConfig(
  config: GitAttributesConfig
): GitAttributesValidationResult {
  const errors: string[] = [];
  const warnings: string[] = [];

  if (
    config.defaultLineEnding === 'none' &&
    !config.enableLfsRules &&
    config.customRules.length === 0
  ) {
    errors.push('At least one normalization or attribute rule must be configured.');
  }

  config.customRules.forEach((rule, idx) => {
    if (!rule.pattern.trim()) {
      errors.push(`Pattern cannot be empty on row #${idx + 1}.`);
    }
    if (!rule.attributes.trim()) {
      errors.push(`Attributes cannot be empty for pattern "${rule.pattern}".`);
    }
  });

  return {
    isValid: errors.length === 0,
    errors,
    warnings,
  };
}

export const GITATTRIBUTES_PRESETS: {
  name: string;
  description: string;
  config: GitAttributesConfig;
}[] = [
  {
    name: 'Universal LF + Git LFS Media & Archive Tracking',
    description: 'Enforce LF endings across Unix/macOS/Windows with LFS for images & archives',
    config: {
      defaultLineEnding: 'lf',
      enableLfsRules: true,
      lfsExtensions: ['png', 'jpg', 'jpeg', 'gif', 'psd', 'mp4', 'zip', 'tar.gz'],
      customRules: [
        {
          id: generateGitAttributeRuleId(),
          pattern: '*.bat',
          attributes: 'text eol=crlf',
          comment: 'Windows batch scripts must use CRLF',
        },
        {
          id: generateGitAttributeRuleId(),
          pattern: '*.sh',
          attributes: 'text eol=lf',
          comment: 'Shell scripts must strictly use LF',
        },
      ],
    },
  },
  {
    name: 'GitHub Linguist & Generated File Suppression',
    description: 'Mark build artifacts and vendor files so GitHub stats stay clean',
    config: {
      defaultLineEnding: 'auto',
      enableLfsRules: false,
      lfsExtensions: [],
      customRules: [
        {
          id: generateGitAttributeRuleId(),
          pattern: 'dist/**',
          attributes: 'linguist-generated=true',
          comment: 'Exclude compiled bundle files from GitHub language stats',
        },
        {
          id: generateGitAttributeRuleId(),
          pattern: 'vendor/**',
          attributes: 'linguist-vendored=true',
          comment: 'Exclude third-party vendor code',
        },
      ],
    },
  },
];
