// ==============================================
// DevForge — Git Hook Builder (Husky / Lefthook)
// ==============================================
// Generate production-grade Git hook scripts
// (pre-commit, commit-msg, pre-push) for modern
// Husky v9+ or Lefthook workflows.
// ==============================================

export type GitHookRunner = 'husky-v9' | 'lefthook' | 'raw-shell';

export interface GitHookRule {
  id: string;
  hookType: 'pre-commit' | 'commit-msg' | 'pre-push';
  command: string;
  enabled: boolean;
  comment?: string;
}

export interface HuskyConfig {
  runner: GitHookRunner;
  packageManager: 'npm' | 'pnpm' | 'yarn' | 'bun';
  hooks: GitHookRule[];
}

export interface HuskyValidationResult {
  isValid: boolean;
  errors: string[];
  warnings: string[];
}

let hookCounter = 1;
export function generateGitHookRuleId(): string {
  return `hook_${Date.now()}_${hookCounter++}`;
}

/**
 * Generates formatted hook file output or Lefthook YAML file based on config.
 */
export function generateGitHookOutput(config: HuskyConfig): string {
  if (config.runner === 'lefthook') {
    const lines: string[] = [];
    lines.push('# lefthook.yml generated by DevForge');
    lines.push('');

    const grouped: Record<string, GitHookRule[]> = {};
    config.hooks
      .filter((h) => h.enabled)
      .forEach((h) => {
        if (!grouped[h.hookType]) grouped[h.hookType] = [];
        grouped[h.hookType].push(h);
      });

    Object.entries(grouped).forEach(([hookName, rules]) => {
      lines.push(`${hookName}:`);
      lines.push('  commands:');
      rules.forEach((rule, idx) => {
        if (rule.comment) {
          lines.push(`    # ${rule.comment}`);
        }
        lines.push(`    step_${idx + 1}:`);
        lines.push(`      run: ${rule.command}`);
      });
      lines.push('');
    });

    return lines.join('\n').trim();
  }

  // Husky v9+ or raw-shell
  const lines: string[] = [];
  lines.push('#!/usr/bin/env sh');
  lines.push('. "$(dirname -- "$0")/_/husky.sh"');
  lines.push('');

  config.hooks
    .filter((h) => h.enabled)
    .forEach((rule) => {
      if (rule.comment) {
        lines.push(`# [${rule.hookType}] ${rule.comment}`);
      }
      lines.push(rule.command);
      lines.push('');
    });

  return lines.join('\n').trim();
}

/**
 * Generates setup CLI commands for the chosen package manager and runner.
 */
export function generateHookInstallCommands(config: HuskyConfig): string {
  const pm = config.packageManager;
  const runner = config.runner;

  if (runner === 'lefthook') {
    const installCmd =
      pm === 'npm'
        ? 'npm install -D lefthook'
        : pm === 'pnpm'
          ? 'pnpm add -D lefthook'
          : pm === 'yarn'
            ? 'yarn add -D lefthook'
            : 'bun add -d lefthook';
    return `${installCmd}\nnpx lefthook install`;
  }

  // husky v9
  const execStr = pm === 'npm' ? 'npx' : pm === 'pnpm' ? 'pnpm dlx' : 'npx';
  return `${execStr} husky init`;
}

/**
 * Validates Git Hook configuration.
 */
export function validateHuskyConfig(config: HuskyConfig): HuskyValidationResult {
  const errors: string[] = [];
  const warnings: string[] = [];

  const enabledHooks = config.hooks.filter((h) => h.enabled);
  if (enabledHooks.length === 0) {
    errors.push('At least one hook rule must be enabled.');
  }

  enabledHooks.forEach((rule) => {
    if (!rule.command.trim()) {
      errors.push(`Command cannot be empty for enabled hook [${rule.hookType}].`);
    }
  });

  return {
    isValid: errors.length === 0,
    errors,
    warnings,
  };
}

export const HUSKY_PRESETS: {
  name: string;
  description: string;
  config: HuskyConfig;
}[] = [
  {
    name: 'Husky v9 Full Quality Guard (Lint + Test + Commitlint)',
    description: 'Pre-commit lint-staged, commit-msg commitlint, pre-push Vitest suite',
    config: {
      runner: 'husky-v9',
      packageManager: 'pnpm',
      hooks: [
        {
          id: generateGitHookRuleId(),
          hookType: 'pre-commit',
          command: 'npx lint-staged',
          enabled: true,
          comment: 'Run fast staged file linting & formatting',
        },
        {
          id: generateGitHookRuleId(),
          hookType: 'commit-msg',
          command: 'npx --no -- commitlint --edit "$1"',
          enabled: true,
          comment: 'Enforce conventional commit message standards',
        },
        {
          id: generateGitHookRuleId(),
          hookType: 'pre-push',
          command: 'pnpm test && pnpm type-check',
          enabled: true,
          comment: 'Validate full test suite and strict TypeScript before pushing',
        },
      ],
    },
  },
  {
    name: 'Lefthook High-Performance YAML Workflow',
    description: 'Fast parallel Git hook steps configured via lefthook.yml',
    config: {
      runner: 'lefthook',
      packageManager: 'pnpm',
      hooks: [
        {
          id: generateGitHookRuleId(),
          hookType: 'pre-commit',
          command: 'pnpm lint',
          enabled: true,
          comment: 'Run ESLint across repository',
        },
        {
          id: generateGitHookRuleId(),
          hookType: 'pre-push',
          command: 'pnpm build',
          enabled: true,
          comment: 'Verify Next.js production bundle build',
        },
      ],
    },
  },
];
