// ==============================================
// DevForge — Pull Request Template Builder Utils
// ==============================================
// Generate standardized .github/PULL_REQUEST_TEMPLATE.md
// with structured review checklists, issue linkage,
// change categories, and verification steps.
// ==============================================

export interface PrTemplateSection {
  id: string;
  title: string;
  enabled: boolean;
  content?: string; // Markdown instruction text
  items?: string[]; // Checklist or bullet items
}

export interface PrTemplateConfig {
  includeIssueLink: boolean;
  includeChangeTypes: boolean;
  changeTypes: string[];
  includeChecklist: boolean;
  checklistItems: string[];
  customSections: PrTemplateSection[];
}

export interface PrTemplateValidationResult {
  isValid: boolean;
  errors: string[];
  warnings: string[];
}

let prSecCounter = 1;
export function generatePrTemplateSectionId(): string {
  return `pr_sec_${Date.now()}_${prSecCounter++}`;
}

/**
 * Generates formatted Markdown PR template based on configuration.
 */
export function generatePrTemplateMarkdown(config: PrTemplateConfig): string {
  const lines: string[] = [];
  lines.push('<!-- Pull Request Template generated by DevForge -->');
  lines.push('');

  lines.push('## 📝 Summary');
  lines.push('<!-- Provide a brief description of the changes and motivation -->');
  lines.push('');

  if (config.includeIssueLink) {
    lines.push('## 🔗 Related Issues');
    lines.push('Closes #<!-- Issue Number -->');
    lines.push('');
  }

  if (config.includeChangeTypes && config.changeTypes.length > 0) {
    lines.push('## 📦 Type of Change');
    lines.push('<!-- Please select the relevant options below -->');
    config.changeTypes.forEach((type) => {
      lines.push(`- [ ] ${type}`);
    });
    lines.push('');
  }

  config.customSections
    .filter((s) => s.enabled)
    .forEach((s) => {
      lines.push(`## ${s.title}`);
      if (s.content?.trim()) {
        lines.push(s.content.trim());
      }
      if (s.items && s.items.length > 0) {
        s.items.forEach((it) => lines.push(`- [ ] ${it}`));
      }
      lines.push('');
    });

  if (config.includeChecklist && config.checklistItems.length > 0) {
    lines.push('## ✅ Verification & Quality Checklist');
    lines.push('<!-- Check all that apply before submitting review -->');
    config.checklistItems.forEach((item) => {
      lines.push(`- [ ] ${item}`);
    });
    lines.push('');
  }

  return lines.join('\n').trim();
}

/**
 * Validates PR template configuration.
 */
export function validatePrTemplateConfig(
  config: PrTemplateConfig
): PrTemplateValidationResult {
  const errors: string[] = [];
  const warnings: string[] = [];

  if (
    !config.includeIssueLink &&
    !config.includeChangeTypes &&
    !config.includeChecklist &&
    config.customSections.filter((s) => s.enabled).length === 0
  ) {
    errors.push('At least one PR template section or checklist must be enabled.');
  }

  return {
    isValid: errors.length === 0,
    errors,
    warnings,
  };
}

export const PR_TEMPLATE_PRESETS: {
  name: string;
  description: string;
  config: PrTemplateConfig;
}[] = [
  {
    name: 'Full Engineering PR Review Standard',
    description: 'Comprehensive template with issue linkage, change types, screenshots, and strict quality checklist',
    config: {
      includeIssueLink: true,
      includeChangeTypes: true,
      changeTypes: [
        '🐛 Bug fix (non-breaking change which fixes an issue)',
        '✨ New feature (non-breaking change which adds functionality)',
        '💥 Breaking change (fix or feature requiring API/data migration)',
        '📚 Documentation update or refactor',
      ],
      includeChecklist: true,
      checklistItems: [
        'My code follows the strict TypeScript & architecture standards',
        'I have run `pnpm lint` and `pnpm type-check` with 0 errors',
        'I have added Vitest unit tests verifying new functionality',
        'All existing tests pass locally (`pnpm test`)',
      ],
      customSections: [
        {
          id: generatePrTemplateSectionId(),
          title: '📸 Visual Evidence / Screenshots',
          enabled: true,
          content: '<!-- Attach before/after screenshots or screen recordings if UI changed -->\n| Before | After |\n| --- | --- |\n| N/A | N/A |',
        },
      ],
    },
  },
  {
    name: 'Concise Agile PR Template',
    description: 'Streamlined template focusing on summary, ticket number, and fast verification',
    config: {
      includeIssueLink: true,
      includeChangeTypes: false,
      changeTypes: [],
      includeChecklist: true,
      checklistItems: [
        'Code self-reviewed',
        'Tests added or updated',
        'No breaking changes introduced',
      ],
      customSections: [],
    },
  },
];
