import React from 'react';
import { registerTool } from './tool-registry';
import type { ToolDefinition } from './tool-types';
import { JsonFormatterPro } from '@/components/tools/json-formatter';
import { JwtDecoderPro } from '@/components/tools/jwt-decoder';
import { Base64StudioPro } from '@/components/tools/base64-studio';
import { RegexStudioPro } from '@/components/tools/regex-studio';
import { YamlFormatterPro } from '@/components/tools/yaml-formatter';
import { XmlFormatterPro } from '@/components/tools/xml-formatter';
import { SqlFormatterPro } from '@/components/tools/sql-formatter';
import { DockerComposeBuilderPro } from '@/components/tools/docker-compose-builder';
import { GitIgnoreGeneratorPro } from '@/components/tools/gitignore-generator';
import { DockerfileBuilderPro } from '@/components/tools/dockerfile-builder';
import { DockerignoreGeneratorPro } from '@/components/tools/dockerignore-generator';
import { EnvBuilderPro } from '@/components/tools/env-builder';
import { KubernetesBuilderPro } from '@/components/tools/kubernetes-builder';
import { NginxBuilderPro } from '@/components/tools/nginx-builder';
import { TraefikBuilderPro } from '@/components/tools/traefik-builder';
import { GitHubActionsBuilderPro } from '@/components/tools/github-actions-builder';
import { DockerRunBuilderPro } from '@/components/tools/docker-run-builder';
import { ReadmeGeneratorPro } from '@/components/tools/readme-generator';
import { ConventionalCommitPro } from '@/components/tools/conventional-commit';
import { GitAliasBuilderPro } from '@/components/tools/git-alias-builder';
import { ReleaseNotesGeneratorPro } from '@/components/tools/release-notes-generator';
import { GitHookBuilderPro } from '@/components/tools/git-hook-builder';
import { GitCheatSheetPro } from '@/components/tools/git-cheat-sheet';
import { GitAttributesGeneratorPro } from '@/components/tools/gitattributes-generator';
import { GitHubLabelsGeneratorPro } from '@/components/tools/github-labels-generator';
import { IssueTemplateBuilderPro } from '@/components/tools/issue-template-builder';
import { PrTemplateBuilderPro } from '@/components/tools/pr-template-builder';
import { ChmodCalculatorPro } from '@/components/tools/chmod-calculator';
import { ChownBuilderPro } from '@/components/tools/chown-builder';
import { CronBuilderPro } from '@/components/tools/cron-builder';
import { SystemdBuilderPro } from '@/components/tools/systemd-builder';
import { BashScriptGeneratorPro } from '@/components/tools/bash-script-generator';
import { SshConfigBuilderPro } from '@/components/tools/ssh-config-builder';
import { SshConfigValidatorPro } from '@/components/tools/ssh-config-validator';
import { SshKeyViewerPro } from '@/components/tools/ssh-key-viewer';
import { ApacheBuilderPro } from '@/components/tools/apache-builder';
import { CaddyBuilderPro } from '@/components/tools/caddy-builder';
import { LinuxCommandExplorerPro } from '@/components/tools/linux-command-explorer';
import { RestRequestBuilderPro } from '@/components/tools/rest-request-builder';
import { HttpHeaderInspectorPro } from '@/components/tools/http-header-inspector';
import { DnsLookupToolPro } from '@/components/tools/dns-lookup-tool';
import { UrlEncoderDecoderPro } from '@/components/tools/url-encoder-decoder';
import { CurlBuilderPro } from '@/components/tools/curl-builder';
import { WebhookTesterPro } from '@/components/tools/webhook-tester';
import { JsonSchemaBuilderPro } from '@/components/tools/json-schema-builder';
import { OpenApiViewerPro } from '@/components/tools/openapi-viewer';
import { GraphQlExplorerPro } from '@/components/tools/graphql-explorer';
import { ApiAuthHelperPro } from '@/components/tools/api-auth-helper';
import { PasswordGeneratorPro } from '@/components/tools/password-generator';
import { PasswordStrengthPro } from '@/components/tools/password-strength-analyzer';
import { HashGeneratorPro } from '@/components/tools/hash-generator';
import { HmacGeneratorPro } from '@/components/tools/hmac-generator';
import { UuidUlidPro } from '@/components/tools/uuid-ulid-generator';
import { CsrDecoderPro } from '@/components/tools/csr-decoder';
import { CertificateViewerPro } from '@/components/tools/certificate-viewer';
import { JwtInspectorPro } from '@/components/tools/jwt-inspector';
import { Base32Pro } from '@/components/tools/base32-encoder-decoder';
import { HexPro } from '@/components/tools/hex-encoder-decoder';

// Placeholder Component for all tools prior to full implementation
const PlaceholderComponent = () => {
  return React.createElement(
    'div',
    { className: 'p-6 text-center text-muted-foreground' },
    'This tool is currently under construction. Check back in Sprint v0.9/v1.0!'
  );
};

export const mvpTools: ToolDefinition[] = [
  // Formatting
  {
    slug: 'json-formatter',
    name: 'JSON Formatter',
    description: 'Format, beautify, validate, and minify JSON data instantly.',
    category: 'formatting',
    icon: 'Code2',
    tags: ['json', 'format', 'beautify', 'minify', 'pretty'],
    keywords: ['json', 'pretty print', 'format json'],
    shortcut: 'F1',
    version: '1.0.0',
    status: 'stable',
    component: JsonFormatterPro,
  },
  {
    slug: 'json-validator',
    name: 'JSON Validator',
    description: 'Check JSON syntax, find syntax errors, and validate RFC guidelines.',
    category: 'formatting',
    icon: 'CheckCircle',
    tags: ['json', 'validate', 'lint', 'syntax'],
    keywords: ['json lint', 'validate json'],
    version: '1.0.0',
    status: 'stable',
    component: PlaceholderComponent,
  },
  {
    slug: 'xml-formatter',
    name: 'XML Formatter',
    description: 'Format, prettify, and prettify XML documents.',
    category: 'formatting',
    icon: 'Code',
    tags: ['xml', 'format', 'beautify'],
    keywords: ['xml pretty print', 'xml format'],
    version: '1.0.0',
    status: 'stable',
    component: XmlFormatterPro,
  },
  {
    slug: 'yaml-formatter',
    name: 'YAML Formatter',
    description: 'Beautify, validate, and convert YAML documents.',
    category: 'formatting',
    icon: 'FileCode',
    tags: ['yaml', 'format', 'beautify'],
    keywords: ['yaml pretty', 'yaml format'],
    version: '1.0.0',
    status: 'stable',
    component: YamlFormatterPro,
  },
  {
    slug: 'sql-formatter',
    name: 'SQL Formatter',
    description: 'Format and prettify raw SQL queries with custom rules.',
    category: 'formatting',
    icon: 'Database',
    tags: ['sql', 'format', 'pretty'],
    keywords: ['sql format', 'beautify sql'],
    version: '1.0.0',
    status: 'stable',
    component: SqlFormatterPro,
  },

  // Encoding
  {
    slug: 'base64',
    name: 'Base64 Encoder/Decoder',
    description: 'Encode plain text or files to Base64 or decode Base64 back.',
    category: 'encoding',
    icon: 'Binary',
    tags: ['base64', 'encode', 'decode'],
    keywords: ['base64 encode', 'base64 decode'],
    shortcut: 'F2',
    version: '1.0.0',
    status: 'stable',
    component: Base64StudioPro,
  },
  {
    slug: 'base64-studio',
    name: 'Base64 Studio Pro',
    description: 'Encode, decode, and inspect text, images, JSON, and binary files with smart MIME detection.',
    category: 'encoding',
    icon: 'Binary',
    tags: ['base64', 'studio', 'encode', 'decode'],
    keywords: ['base64 studio', 'encode file', 'decode image'],
    version: '1.0.0',
    status: 'stable',
    component: Base64StudioPro,
  },
  {
    slug: 'jwt-decoder',
    name: 'JWT Decoder',
    description: 'Decode and inspect JSON Web Tokens (JWT) payload, header, and signature.',
    category: 'encoding',
    icon: 'ShieldAlert',
    tags: ['jwt', 'decode', 'token', 'auth'],
    keywords: ['jwt', 'token', 'decode jwt'],
    shortcut: 'F3',
    version: '1.0.0',
    status: 'stable',
    component: JwtDecoderPro,
  },

  // Generators
  {
    slug: 'uuid-generator',
    name: 'UUID Generator',
    description: 'Generate secure cryptographically random UUIDs (v4 and v7).',
    category: 'generators',
    icon: 'Fingerprint',
    tags: ['uuid', 'guid', 'generate', 'random'],
    keywords: ['uuid', 'guid', 'generate uuid'],
    shortcut: 'F4',
    version: '1.0.0',
    status: 'stable',
    component: PlaceholderComponent,
  },
  {
    slug: 'password-generator',
    name: 'Password Generator',
    description: 'Generate highly secure custom random passwords.',
    category: 'generators',
    icon: 'Key',
    tags: ['password', 'generate', 'security', 'random'],
    keywords: ['password', 'generate password'],
    version: '1.0.0',
    status: 'stable',
    component: PlaceholderComponent,
  },
  {
    slug: 'dockerfile-generator',
    name: 'Dockerfile Generator',
    description: 'Interactive builder to generate optimized Dockerfiles for various stacks.',
    category: 'docker',
    icon: 'FilePlus',
    tags: ['docker', 'dockerfile', 'generator'],
    keywords: ['dockerfile', 'docker file'],
    shortcut: 'F5',
    version: '1.0.0',
    status: 'beta',
    component: PlaceholderComponent,
  },

  // Linux
  {
    slug: 'chmod-calculator',
    name: 'chmod Calculator',
    description: 'Interactive calculator for chmod permissions with numerical and symbolic notation.',
    category: 'linux',
    icon: 'Sliders',
    tags: ['chmod', 'permissions', 'linux', 'octal'],
    keywords: ['chmod', 'octal permissions'],
    version: '1.0.0',
    status: 'stable',
    component: PlaceholderComponent,
  },

  // Git
  {
    slug: 'conventional-commits',
    name: 'Conventional Commits Builder',
    description: 'Interactive wizard to build conventional commit messages.',
    category: 'git',
    icon: 'GitCommit',
    tags: ['git', 'commit', 'conventional'],
    keywords: ['conventional commit', 'git commit helper'],
    version: '1.0.0',
    status: 'stable',
    component: PlaceholderComponent,
  },

  // Utilities
  {
    slug: 'regex-tester',
    name: 'Regex Tester',
    description: 'Test, build, and debug regular expressions with highlighting and explanation.',
    category: 'utilities',
    icon: 'Regex',
    tags: ['regex', 'test', 'match', 'expression'],
    keywords: ['regex tester', 'regex test'],
    shortcut: 'F6',
    version: '1.0.0',
    status: 'stable',
    component: RegexStudioPro,
  },
  {
    slug: 'regex-studio',
    name: 'Regex Studio Pro',
    description: 'Design, test, and debug regular expressions with live group captures, flag toggles, and preset library.',
    category: 'utilities',
    icon: 'Regex',
    tags: ['regex', 'studio', 'match', 'replace'],
    keywords: ['regex studio', 'regex replace', 'test regex'],
    version: '1.0.0',
    status: 'stable',
    component: RegexStudioPro,
  },

  // Docker
  {
    slug: 'docker-compose-builder',
    name: 'Docker Compose Builder Pro',
    description: 'Visual Docker Compose builder with live YAML generation, validation, and production-ready templates.',
    category: 'docker',
    icon: 'Container',
    tags: ['docker', 'compose', 'builder', 'yaml'],
    keywords: ['docker compose', 'docker-compose builder'],
    version: '1.0.0',
    status: 'stable',
    component: DockerComposeBuilderPro,
  },

  // Git
  {
    slug: 'gitignore-generator',
    name: 'GitIgnore Generator Pro',
    description: 'Generate production-ready .gitignore files for any technology stack with smart deduplication.',
    category: 'git',
    icon: 'FileX',
    tags: ['gitignore', 'generator', 'git'],
    keywords: ['gitignore generator', 'gitignore'],
    version: '1.0.0',
    status: 'stable',
    component: GitIgnoreGeneratorPro,
  },
  {
    slug: 'dockerfile-builder',
    name: 'Dockerfile Builder Pro',
    description: 'Visual multi-stage Dockerfile generator with live preview, security checks, and cross-tool .dockerignore suggestions.',
    category: 'docker',
    icon: 'Container',
    tags: ['docker', 'dockerfile', 'builder', 'multi-stage'],
    keywords: ['dockerfile builder', 'create dockerfile', 'docker build'],
    version: '1.0.0',
    status: 'stable',
    component: DockerfileBuilderPro,
  },
  {
    slug: 'dockerignore-generator',
    name: '.dockerignore Generator Pro',
    description: 'Generate comprehensive, highly-secure .dockerignore files to prevent secret leakage and optimize build cache.',
    category: 'docker',
    icon: 'FileX',
    tags: ['docker', 'dockerignore', 'security', 'cache'],
    keywords: ['dockerignore generator', 'docker ignore'],
    version: '1.0.0',
    status: 'stable',
    component: DockerignoreGeneratorPro,
  },
  {
    slug: 'env-builder',
    name: 'Environment (.env) Builder Pro',
    description: 'Visual .env file editor with secret masking, .env.example generator, validation, and Docker Compose integration.',
    category: 'devops',
    icon: 'Shield',
    tags: ['env', 'environment', 'secrets', 'devops'],
    keywords: ['env builder', 'dotenv', 'environment variables'],
    version: '1.0.0',
    status: 'stable',
    component: EnvBuilderPro,
  },
  {
    slug: 'kubernetes-builder',
    name: 'Kubernetes Manifest Builder Pro',
    description: 'Visual Kubernetes Deployment, Service, and Ingress manifest generator with resource limits, TLS, and multi-document YAML export.',
    category: 'devops',
    icon: 'Layers',
    tags: ['kubernetes', 'k8s', 'deployment', 'devops', 'manifest'],
    keywords: ['kubernetes builder', 'k8s manifest', 'k8s generator'],
    version: '1.0.0',
    status: 'stable',
    component: KubernetesBuilderPro,
  },
  {
    slug: 'nginx-builder',
    name: 'Nginx Config Builder Pro',
    description: 'Visual Nginx server block builder for reverse proxies, SPA static site routing, SSL TLSv1.3, and Gzip compression.',
    category: 'devops',
    icon: 'Server',
    tags: ['nginx', 'proxy', 'config', 'devops', 'webserver'],
    keywords: ['nginx config', 'nginx generator', 'reverse proxy'],
    version: '1.0.0',
    status: 'stable',
    component: NginxBuilderPro,
  },
  {
    slug: 'traefik-builder',
    name: 'Traefik Config Builder Pro',
    description: 'Visual Traefik v3 static & dynamic YAML generator with Docker auto-discovery and automated Let\'s Encrypt TLS.',
    category: 'devops',
    icon: 'Network',
    tags: ['traefik', 'proxy', 'ingress', 'acme', 'devops'],
    keywords: ['traefik config', 'traefik yaml', 'traefik generator'],
    version: '1.0.0',
    status: 'stable',
    component: TraefikBuilderPro,
  },
  {
    slug: 'github-actions-builder',
    name: 'GitHub Actions Workflow Builder Pro',
    description: 'Visual CI/CD workflow generator with automated Docker build/push integration, multi-branch triggers, and step matrix builder.',
    category: 'devops',
    icon: 'Play',
    tags: ['github', 'actions', 'cicd', 'workflow', 'devops'],
    keywords: ['github actions', 'ci cd', 'workflow generator'],
    version: '1.0.0',
    status: 'stable',
    component: GitHubActionsBuilderPro,
  },
  {
    slug: 'docker-run-builder',
    name: 'Docker Run Command Builder Pro',
    description: 'Visual docker run CLI command generator with volume mounts, environment flags, interactive mode, and Docker Compose import support.',
    category: 'docker',
    icon: 'Terminal',
    tags: ['docker', 'cli', 'run', 'container', 'devops'],
    keywords: ['docker run', 'docker command', 'cli generator'],
    version: '1.0.0',
    status: 'stable',
    component: DockerRunBuilderPro,
  },
  {
    slug: 'readme-generator',
    name: 'README Generator Pro',
    description: 'Visual README.md document builder with dynamic Shields.io badges, features list, tech stack badges, and table of contents.',
    category: 'git',
    icon: 'FileText',
    tags: ['readme', 'markdown', 'documentation', 'git', 'github'],
    keywords: ['readme generator', 'readme md', 'github readme'],
    version: '1.0.0',
    status: 'stable',
    component: ReadmeGeneratorPro,
  },
  {
    slug: 'conventional-commit',
    name: 'Conventional Commit Assistant',
    description: 'Interactive specification builder for standardized git commit messages with semantic versioning triggers, breaking change flags, and issue reference footers.',
    category: 'git',
    icon: 'GitCommit',
    tags: ['git', 'commit', 'conventional', 'semver', 'changelog'],
    keywords: ['conventional commit', 'git commit', 'commit generator'],
    version: '1.0.0',
    status: 'stable',
    component: ConventionalCommitPro,
  },
  {
    slug: 'git-alias-builder',
    name: 'Git Alias Builder',
    description: 'Visual generator for Git terminal shortcuts supporting .gitconfig INI sections, global CLI setup commands, and shell bash/zsh aliases.',
    category: 'git',
    icon: 'Terminal',
    tags: ['git', 'alias', 'gitconfig', 'shortcuts', 'terminal'],
    keywords: ['git alias', 'git shortcuts', 'gitconfig alias'],
    version: '1.0.0',
    status: 'stable',
    component: GitAliasBuilderPro,
  },
  {
    slug: 'release-notes-generator',
    name: 'Release Notes Generator',
    description: 'Automated changelog builder that parses git log --oneline output and groups commits into semantic categories with GitHub comparison links.',
    category: 'git',
    icon: 'FileText',
    tags: ['git', 'release', 'changelog', 'notes', 'github'],
    keywords: ['release notes', 'changelog generator', 'git log parser'],
    version: '1.0.0',
    status: 'stable',
    component: ReleaseNotesGeneratorPro,
  },
  {
    slug: 'git-hook-builder',
    name: 'Git Hook Builder (Husky)',
    description: 'Interactive generator for Husky v9+, Lefthook YAML workflows, and raw git hook scripts covering pre-commit linting, commit-msg checks, and pre-push validation.',
    category: 'git',
    icon: 'ShieldCheck',
    tags: ['git', 'husky', 'hooks', 'lefthook', 'pre-commit', 'lint-staged'],
    keywords: ['husky builder', 'git hooks', 'pre-commit generator'],
    version: '1.0.0',
    status: 'stable',
    component: GitHookBuilderPro,
  },
  {
    slug: 'git-cheat-sheet',
    name: 'Interactive Git Cheat Sheet',
    description: 'Searchable reference guide for Git workflows with live parameter substitution, safety risk indicators, and one-click terminal commands.',
    category: 'git',
    icon: 'Terminal',
    tags: ['git', 'cheat sheet', 'commands', 'reference', 'cli'],
    keywords: ['git cheat sheet', 'git reference', 'git commands'],
    version: '1.0.0',
    status: 'stable',
    component: GitCheatSheetPro,
  },
  {
    slug: 'gitattributes-generator',
    name: '.gitattributes Generator',
    description: 'Visual builder for Git repository normalization covering line ending conversions (LF/CRLF), Git LFS large asset tracking, and GitHub Linguist stats override rules.',
    category: 'git',
    icon: 'FileCode',
    tags: ['git', 'gitattributes', 'lfs', 'line endings', 'crlf', 'linguist'],
    keywords: ['gitattributes generator', 'git lfs config', 'crlf normalization'],
    version: '1.0.0',
    status: 'stable',
    component: GitAttributesGeneratorPro,
  },
  {
    slug: 'github-labels-generator',
    name: 'GitHub Labels Generator',
    description: 'Visual builder for repository issue & PR labels with hex color previews, exporting to GitHub CLI script commands, JSON arrays, or YAML configs.',
    category: 'git',
    icon: 'Tag',
    tags: ['git', 'github', 'labels', 'issues', 'gh-cli', 'triage'],
    keywords: ['github labels generator', 'gh label create', 'issue triage labels'],
    version: '1.0.0',
    status: 'stable',
    component: GitHubLabelsGeneratorPro,
  },
  {
    slug: 'issue-template-builder',
    name: 'GitHub Issue Template Builder',
    description: 'Visual builder for GitHub YAML Issue Forms (.yml) and Markdown templates (.md) with structured fields, dropdown selectors, checkboxes, and required validation rules.',
    category: 'git',
    icon: 'FileSpreadsheet',
    tags: ['git', 'github', 'issue template', 'yaml form', 'bug report'],
    keywords: ['issue template builder', 'github issue form', 'bug report template'],
    version: '1.0.0',
    status: 'stable',
    component: IssueTemplateBuilderPro,
  },
  {
    slug: 'pr-template-builder',
    name: 'Pull Request Template Builder',
    description: 'Interactive generator for .github/PULL_REQUEST_TEMPLATE.md with structured review checklists, issue linkage, change type categories, and quality verification steps.',
    category: 'git',
    icon: 'CheckSquare',
    tags: ['git', 'github', 'pr template', 'pull request', 'code review', 'checklist'],
    keywords: ['pr template builder', 'pull request template', 'github pr checklist'],
    version: '1.0.0',
    status: 'stable',
    component: PrTemplateBuilderPro,
  },
  {
    slug: 'chmod-calculator',
    name: 'chmod Calculator Pro',
    description: 'Interactive Linux permission matrix calculator with bidirectional Octal (755) and Symbolic (-rwxr-xr-x) conversion, special bits (SUID/SGID/Sticky), and CLI chmod command builder.',
    category: 'linux',
    icon: 'ShieldCheck',
    tags: ['linux', 'chmod', 'permissions', 'octal', 'symbolic', 'suid'],
    keywords: ['chmod calculator', 'linux permissions', 'octal 755', 'chmod command'],
    version: '1.0.0',
    status: 'stable',
    component: ChmodCalculatorPro,
  },
  {
    slug: 'chown-builder',
    name: 'chown Command Builder',
    description: 'Interactive Linux chown & chgrp command generator with recursive ownership rules, UID/GID syntax, symlink dereference options, and preserve-root safeguards.',
    category: 'linux',
    icon: 'UserCheck',
    tags: ['linux', 'chown', 'chgrp', 'ownership', 'uid', 'gid', 'www-data'],
    keywords: ['chown command builder', 'linux ownership', 'chown -R www-data'],
    version: '1.0.0',
    status: 'stable',
    component: ChownBuilderPro,
  },
  {
    slug: 'cron-builder',
    name: 'Cron Expression Builder',
    description: 'Interactive 5-field Linux crontab schedule generator with human-readable natural language descriptor, execution presets, and system user crontab formatting.',
    category: 'linux',
    icon: 'Clock',
    tags: ['linux', 'cron', 'crontab', 'schedule', 'expression', 'timer'],
    keywords: ['cron expression builder', 'crontab generator', 'cron schedule explain'],
    version: '1.0.0',
    status: 'stable',
    component: CronBuilderPro,
  },
  {
    slug: 'systemd-builder',
    name: 'Systemd Service Builder',
    description: 'Visual generator for Linux .service unit files with security hardening flags, environment variables, restart policies, and systemctl lifecycle commands.',
    category: 'linux',
    icon: 'Cpu',
    tags: ['linux', 'systemd', 'service', 'daemon', 'unit', 'systemctl'],
    keywords: ['systemd service builder', 'linux unit file', 'systemctl enable service'],
    version: '1.0.0',
    status: 'stable',
    component: SystemdBuilderPro,
  },
  {
    slug: 'bash-script-generator',
    name: 'Bash Script Generator',
    description: 'Interactive generator for production-grade Linux Bash scripts with strict mode (set -euo pipefail), ANSI logging helpers, trap cleanup handlers, and CLI flag parsers.',
    category: 'linux',
    icon: 'Terminal',
    tags: ['linux', 'bash', 'shell', 'script', 'boilerplate', 'trap'],
    keywords: ['bash script generator', 'linux shell script', 'bash boilerplate set -euo pipefail'],
    version: '1.0.0',
    status: 'stable',
    component: BashScriptGeneratorPro,
  },
  {
    slug: 'ssh-config-builder',
    name: 'SSH Config Builder',
    description: 'Visual multi-host generator for ~/.ssh/config supporting ProxyJump bastion routing, IdentityFile selection, LocalForward SSH tunnels, and keep-alive intervals.',
    category: 'linux',
    icon: 'Key',
    tags: ['linux', 'ssh', 'config', 'proxyjump', 'bastion', 'tunnel'],
    keywords: ['ssh config builder', 'ssh proxyjump bastion', 'ssh config multi host'],
    version: '1.0.0',
    status: 'stable',
    component: SshConfigBuilderPro,
  },
  {
    slug: 'ssh-config-validator',
    name: 'SSH Config Validator',
    description: 'Interactive ~/.ssh/config security scanner and syntax linter detecting duplicate Host aliases, wildcard shadowing, Agent Forwarding risks, and formatting issues.',
    category: 'linux',
    icon: 'ShieldCheck',
    tags: ['linux', 'ssh', 'config', 'validator', 'scanner', 'linter'],
    keywords: ['ssh config validator', 'ssh config linter', 'check ~/.ssh/config'],
    version: '1.0.0',
    status: 'stable',
    component: SshConfigValidatorPro,
  },
  {
    slug: 'ssh-key-viewer',
    name: 'SSH Key Viewer',
    description: 'Cryptographic inspection tool for SSH public and private keys to identify algorithm, estimate bit strength, verify passphrase protection, and extract email comments.',
    category: 'linux',
    icon: 'KeyRound',
    tags: ['linux', 'ssh', 'key', 'pubkey', 'ed25519', 'rsa', 'inspector'],
    keywords: ['ssh key viewer', 'inspect ssh public key', 'check ssh key type ed25519'],
    version: '1.0.0',
    status: 'stable',
    component: SshKeyViewerPro,
  },
  {
    slug: 'apache-builder',
    name: 'Apache Virtual Host Builder',
    description: 'Visual generator for Apache 2.4 VirtualHost configurations with SSL/TLS certificates, mod_proxy reverse proxying, AllowOverride .htaccess permissions, and HTTP redirect blocks.',
    category: 'linux',
    icon: 'Globe',
    tags: ['linux', 'apache', 'virtualhost', 'httpd', 'vhost', 'mod_proxy'],
    keywords: ['apache virtual host builder', 'apache reverse proxy', 'apache ssl vhost conf'],
    version: '1.0.0',
    status: 'stable',
    component: ApacheBuilderPro,
  },
  {
    slug: 'caddy-builder',
    name: 'Caddy Config Builder',
    description: 'Visual Caddyfile generator for Caddy v2 with automatic Let\'s Encrypt HTTPS, reverse proxy routing, static file SPA servers, gzip/zstd compression, and security headers.',
    category: 'linux',
    icon: 'Zap',
    tags: ['linux', 'caddy', 'caddyfile', 'proxy', 'https', 'acme'],
    keywords: ['caddy config builder', 'caddyfile reverse proxy', 'caddy automatic https'],
    version: '1.0.0',
    status: 'stable',
    component: CaddyBuilderPro,
  },
  {
    slug: 'linux-command-explorer',
    name: 'Linux Command Explorer',
    description: 'Interactive Linux server administration and DevOps CLI database with flag reference breakdowns, syntax templates, and real-world production examples.',
    category: 'linux',
    icon: 'Terminal',
    tags: ['linux', 'cli', 'command', 'bash', 'devops', 'reference', 'cheatsheet'],
    keywords: ['linux command explorer', 'devops linux commands', 'ps aux lsof ss curl chmod reference'],
    version: '1.0.0',
    status: 'stable',
    component: LinuxCommandExplorerPro,
  },
  {
    slug: 'rest-request-builder',
    name: 'REST Request Builder',
    description: 'Interactive REST API client configuration tool generating multi-language code snippets (cURL, fetch, Axios, Python) with query parameter builder and live response simulator.',
    category: 'api',
    icon: 'Globe',
    tags: ['api', 'rest', 'http', 'curl', 'fetch', 'axios', 'request'],
    keywords: ['rest request builder', 'api client curl generator', 'http request builder'],
    version: '1.0.0',
    status: 'stable',
    component: RestRequestBuilderPro,
  },
  {
    slug: 'http-header-inspector',
    name: 'HTTP Header Inspector',
    description: 'Analyze raw HTTP response headers, evaluate OWASP security posture (HSTS, CSP, X-Frame-Options, nosniff), detect technology stack leaks, and grade security rating.',
    category: 'network',
    icon: 'ShieldAlert',
    tags: ['network', 'http', 'headers', 'security', 'owasp', 'hsts', 'csp'],
    keywords: ['http header inspector', 'owasp header check', 'security header scanner'],
    version: '1.0.0',
    status: 'stable',
    component: HttpHeaderInspectorPro,
  },
  {
    slug: 'dns-lookup-tool',
    name: 'DNS Lookup Tool',
    description: 'Inspect domain DNS records (A, AAAA, MX, TXT, NS, CAA), generate CLI lookup commands (dig, nslookup, host), and audit email authentication records (SPF & DMARC).',
    category: 'network',
    icon: 'Globe',
    tags: ['network', 'dns', 'lookup', 'dig', 'nslookup', 'spf', 'dmarc', 'caa'],
    keywords: ['dns lookup tool', 'dig command generator', 'spf dmarc checker'],
    version: '1.0.0',
    status: 'stable',
    component: DnsLookupToolPro,
  },
  {
    slug: 'url-encoder-decoder',
    name: 'URL Encoder / Decoder',
    description: 'Encode and decode URLs, URI components, and query parameters with RFC 3986 and form-data (+) modes, plus interactive URL structure and query parameter inspection.',
    category: 'encoding',
    icon: 'Link2',
    tags: ['encoding', 'url', 'uri', 'encode', 'decode', 'query'],
    keywords: ['url encoder decoder', 'encodeuricomponent', 'url decode online'],
    version: '1.0.0',
    status: 'stable',
    component: UrlEncoderDecoderPro,
  },
  {
    slug: 'curl-builder',
    name: 'cURL Command Builder',
    description: 'Construct multi-line or single-line cURL CLI commands and JS fetch() snippets with headers, authentication, payload body, SSL bypass (-k), and redirect flags (-L).',
    category: 'api',
    icon: 'Terminal',
    tags: ['api', 'curl', 'http', 'command', 'fetch', 'rest'],
    keywords: ['curl command builder', 'generate curl', 'curl generator online'],
    version: '1.0.0',
    status: 'stable',
    component: CurlBuilderPro,
  },
  {
    slug: 'webhook-tester',
    name: 'Webhook Tester & Payload Simulator',
    description: 'Simulate webhook deliveries from GitHub, Stripe, and Slack, audit headers, verify HMAC-SHA256 signature hashes, and generate replay cURL commands.',
    category: 'api',
    icon: 'Webhook',
    tags: ['api', 'webhook', 'hmac', 'signature', 'payload', 'event'],
    keywords: ['webhook tester', 'hmac sha256 verify', 'webhook simulator'],
    version: '1.0.0',
    status: 'stable',
    component: WebhookTesterPro,
  },
  {
    slug: 'json-schema-builder',
    name: 'JSON Schema Builder & Validator',
    description: 'Infer JSON Schema Draft-07 automatically from sample JSON data, generate TypeScript Interface definitions, and structurally validate JSON instances.',
    category: 'api',
    icon: 'FileJson',
    tags: ['api', 'json', 'schema', 'typescript', 'validate', 'draft-07'],
    keywords: ['json schema builder', 'json to schema online', 'validate json schema'],
    version: '1.0.0',
    status: 'stable',
    component: JsonSchemaBuilderPro,
  },
  {
    slug: 'openapi-viewer',
    name: 'OpenAPI / Swagger Endpoint Viewer',
    description: 'Inspect OpenAPI 3.0 and Swagger API specifications, browse endpoint routes, view parameter schemas, and generate cURL test commands.',
    category: 'api',
    icon: 'FileCode',
    tags: ['api', 'openapi', 'swagger', 'endpoints', 'documentation', 'rest'],
    keywords: ['openapi viewer online', 'swagger viewer', 'inspect openapi endpoints'],
    version: '1.0.0',
    status: 'stable',
    component: OpenApiViewerPro,
  },
  {
    slug: 'graphql-explorer',
    name: 'GraphQL Explorer & Query Builder',
    description: 'Construct GraphQL queries and mutations, format operation syntax, define query variables, and generate HTTP execution cURL scripts.',
    category: 'api',
    icon: 'Database',
    tags: ['api', 'graphql', 'query', 'mutation', 'schema', 'fetch'],
    keywords: ['graphql explorer online', 'graphql query builder', 'format graphql'],
    version: '1.0.0',
    status: 'stable',
    component: GraphQlExplorerPro,
  },
  {
    slug: 'api-auth-helper',
    name: 'API Authentication Helper & Header Generator',
    description: 'Generate HTTP authentication headers (Bearer JWT, Basic Base64, Custom API Keys, OAuth 2.0 Client Credentials), cURL test scripts, and JS fetch snippets.',
    category: 'api',
    icon: 'KeyRound',
    tags: ['api', 'auth', 'authentication', 'bearer', 'basic', 'oauth2', 'headers'],
    keywords: ['api auth helper', 'generate basic auth header', 'bearer token header generator'],
    version: '1.0.0',
    status: 'stable',
    component: ApiAuthHelperPro,
  },
  {
    slug: 'password-generator',
    name: 'Password & Passphrase Generator Pro',
    description: 'Generate cryptographically secure random passwords and word passphrases locally with entropy bits calculation and crack resistance scoring.',
    category: 'security',
    icon: 'KeyRound',
    tags: ['security', 'password', 'passphrase', 'generator', 'entropy', 'crypto'],
    keywords: ['password generator online', 'secure passphrase generator', 'calculate password entropy'],
    version: '1.0.0',
    status: 'stable',
    component: PasswordGeneratorPro,
  },
  {
    slug: 'password-strength-analyzer',
    name: 'Password Strength Analyzer & Entropy Auditor',
    description: 'Evaluate password cryptographic entropy, detect dictionary flaws, check character composition, and estimate offline GPU crack time locally.',
    category: 'security',
    icon: 'ShieldCheck',
    tags: ['security', 'password', 'strength', 'analyzer', 'entropy', 'audit'],
    keywords: ['password strength analyzer online', 'password entropy checker', 'how long to crack password'],
    version: '1.0.0',
    status: 'stable',
    component: PasswordStrengthPro,
  },
  {
    slug: 'hash-generator',
    name: 'Cryptographic Hash Generator (SHA-1 / SHA-256 / SHA-512)',
    description: 'Compute locally-secure SHA digests via Web Crypto API, compare verification checksums, and export formatted hexadecimal hashes.',
    category: 'security',
    icon: 'Hash',
    tags: ['security', 'hash', 'sha1', 'sha256', 'sha512', 'checksum', 'crypto'],
    keywords: ['hash generator online', 'sha256 hash generator', 'compare sha checksum'],
    version: '1.0.0',
    status: 'stable',
    component: HashGeneratorPro,
  },
  {
    slug: 'hmac-generator',
    name: 'HMAC Generator & Signature Verifier',
    description: 'Compute cryptographic HMAC-SHA1, HMAC-SHA256, and HMAC-SHA512 signatures locally, compare webhook digests, and export Hex or Base64 signatures.',
    category: 'security',
    icon: 'KeyRound',
    tags: ['security', 'hmac', 'sha256', 'signature', 'webhook', 'stripe', 'verifier'],
    keywords: ['hmac generator online', 'verify stripe webhook signature', 'generate hmac sha256'],
    version: '1.0.0',
    status: 'stable',
    component: HmacGeneratorPro,
  },
  {
    slug: 'uuid-ulid-generator',
    name: 'UUID v4 / UUID v7 / ULID Generator & Timestamp Decoder',
    description: 'Generate standard random UUID v4, time-ordered RFC 9562 UUID v7, and sortable 26-char ULIDs, plus extract embedded creation timestamps.',
    category: 'security',
    icon: 'Hash',
    tags: ['security', 'uuid', 'uuidv4', 'uuidv7', 'ulid', 'generator', 'decoder', 'timestamp'],
    keywords: ['uuid v7 generator online', 'ulid generator', 'decode uuid v7 timestamp'],
    version: '1.0.0',
    status: 'stable',
    component: UuidUlidPro,
  },
  {
    slug: 'csr-decoder',
    name: 'X.509 Certificate Signing Request (CSR) Decoder',
    description: 'Inspect PEM-encoded PKCS#10 Certificate Signing Requests to verify Common Name (CN), SANs, Organization fields, and RSA/ECDSA key size.',
    category: 'security',
    icon: 'FileCode2',
    tags: ['security', 'csr', 'ssl', 'tls', 'certificate', 'decoder', 'x509', 'pem'],
    keywords: ['csr decoder online', 'check csr common name', 'verify csr subject alternative names'],
    version: '1.0.0',
    status: 'stable',
    component: CsrDecoderPro,
  },
  {
    slug: 'certificate-viewer',
    name: 'X.509 Certificate Viewer & SSL Chain Auditor',
    description: 'Inspect PEM X.509 SSL/TLS certificates to audit expiration dates, issuer authority, SANs, serial numbers, and SHA-256 fingerprints.',
    category: 'security',
    icon: 'FileCheck',
    tags: ['security', 'ssl', 'tls', 'certificate', 'viewer', 'x509', 'expiration', 'pem'],
    keywords: ['ssl certificate decoder online', 'check certificate expiration date', 'inspect pem x509 cert'],
    version: '1.0.0',
    status: 'stable',
    component: CertificateViewerPro,
  },
  {
    slug: 'jwt-inspector',
    name: 'JWT Security Auditor & Flaw Inspector',
    description: 'Perform a comprehensive security audit on JSON Web Tokens to detect alg=none flaws, missing exp claims, PII exposure, and calculate security scores.',
    category: 'security',
    icon: 'KeyRound',
    tags: ['security', 'jwt', 'token', 'auditor', 'inspector', 'vulnerability', 'auth', 'oauth'],
    keywords: ['jwt security auditor online', 'check jwt alg none vulnerability', 'audit jwt token online'],
    version: '1.0.0',
    status: 'stable',
    component: JwtInspectorPro,
  },
  {
    slug: 'base32-encoder-decoder',
    name: 'RFC 4648 Base32 Encoder / Decoder & TOTP Secret Formatter',
    description: 'Encode UTF-8 text into standard RFC 4648 Base32 alphabet (A-Z2-7), decode Base32 secrets, and format 4-character TOTP blocks for Authenticator apps.',
    category: 'security',
    icon: 'Binary',
    tags: ['security', 'base32', 'rfc4648', 'totp', '2fa', 'authenticator', 'encoder', 'decoder'],
    keywords: ['base32 encoder online', 'decode base32 totp secret', 'format base32 authenticator chunks'],
    version: '1.0.0',
    status: 'stable',
    component: Base32Pro,
  },
  {
    slug: 'hex-encoder-decoder',
    name: 'Hexadecimal Encoder / Decoder & Memory Byte Dump Viewer',
    description: 'Encode UTF-8 strings into Hex bytes with custom delimiters (space, colon, 0x), decode Hex payloads, and inspect 16-byte memory hex dumps.',
    category: 'security',
    icon: 'FileCode',
    tags: ['security', 'hex', 'hexadecimal', 'converter', 'encoder', 'decoder', 'hexdump', 'memory'],
    keywords: ['hex encoder online', 'hex dump viewer online', 'string to hexadecimal bytes'],
    version: '1.0.0',
    status: 'stable',
    component: HexPro,
  },
];

// Initialize registry
export function initializeRegistry(): void {
  mvpTools.forEach((tool) => registerTool(tool));
}
