'use client';

import { useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import { motion } from 'framer-motion';
import { ArrowRight, Blocks, Clock3, FolderKanban, Plus, Search, Sparkles, Star, WandSparkles } from 'lucide-react';
import { initializeRegistry } from '@/sdk/tools-init';
import { getAllTools, searchTools } from '@/sdk/tool-registry';
import { categories } from '@/constants/categories';
import { useWorkspace } from '@/components/workspace';

initializeRegistry();

export default function DashboardPage() {
  const router = useRouter();
  const { favorites, historyItems } = useWorkspace();
  const [query, setQuery] = useState('');
  const tools = useMemo(() => getAllTools(), []);
  const results = useMemo(() => (query ? searchTools(query) : tools.slice(0, 6)), [query, tools]);
  const favoriteTools = useMemo(() => tools.filter((tool) => favorites.includes(tool.slug)).slice(0, 3), [favorites, tools]);
  const recentTools = useMemo(() => tools.filter((tool) => historyItems.some((history) => history.toolName === tool.name || history.toolName === tool.slug)).slice(0, 3), [historyItems, tools]);
  const shownTools = query ? results : favoriteTools.length ? favoriteTools : recentTools.length ? recentTools : results.slice(0, 3);

  return <div className="mx-auto w-full max-w-7xl overflow-y-auto px-5 py-8 pb-16 sm:px-8 lg:px-10">
    <motion.section initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="relative overflow-hidden rounded-[24px] border border-white/[.09] bg-gradient-to-br from-violet-300/[.13] via-white/[.045] to-transparent p-6 shadow-2xl shadow-black/15 sm:p-8">
      <div className="absolute -right-20 -top-24 size-64 rounded-full bg-violet-400/15 blur-3xl" />
      <div className="relative"><div className="flex flex-wrap items-center justify-between gap-3"><p className="eyebrow">Your personal workspace</p><span className="inline-flex items-center gap-1.5 rounded-full border border-teal-200/15 bg-teal-300/[.08] px-2.5 py-1 text-[11px] text-teal-200"><span className="size-1.5 rounded-full bg-teal-300" />Local and ready</span></div>
      <h1 className="mt-5 text-3xl font-semibold tracking-[-.045em] text-white sm:text-4xl">Make a little progress.</h1><p className="mt-2 max-w-xl text-sm leading-6 text-zinc-400">Your tools, workspace memory, and recent work — all in one calm place.</p>
      <div className="mt-7 flex max-w-2xl items-center rounded-xl border border-white/[.1] bg-[#0c0c0f]/65 p-1.5 shadow-xl shadow-black/20"><Search className="ml-2 size-4 text-zinc-500" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Find a tool to get started…" className="h-9 min-w-0 flex-1 bg-transparent px-3 text-sm text-white outline-none placeholder:text-zinc-600" /><kbd className="keyboard-key mr-1 hidden sm:block">⌘ K</kbd></div></div>
    </motion.section>

    <div className="mt-8 grid gap-4 md:grid-cols-3"><button onClick={() => router.push('/dashboard/workspace')} className="app-panel-interactive flex min-h-28 items-center gap-4 p-5 text-left"><span className="grid size-10 place-items-center rounded-xl bg-violet-300/15 text-violet-200"><Plus className="size-5" /></span><span><b className="block text-sm font-medium text-zinc-100">New workspace</b><small className="mt-1 block text-xs text-zinc-500">Start a focused session</small></span></button><button onClick={() => router.push('/dashboard/marketplace')} className="app-panel-interactive flex min-h-28 items-center gap-4 p-5 text-left"><span className="grid size-10 place-items-center rounded-xl bg-teal-300/15 text-teal-200"><WandSparkles className="size-5" /></span><span><b className="block text-sm font-medium text-zinc-100">Browse plugins</b><small className="mt-1 block text-xs text-zinc-500">Add a new capability</small></span></button><button onClick={() => router.push('/dashboard/collections')} className="app-panel-interactive flex min-h-28 items-center gap-4 p-5 text-left"><span className="grid size-10 place-items-center rounded-xl bg-amber-200/15 text-amber-100"><FolderKanban className="size-5" /></span><span><b className="block text-sm font-medium text-zinc-100">Organize collections</b><small className="mt-1 block text-xs text-zinc-500">Keep frequent work close</small></span></button></div>

    <section className="mt-10"><div className="flex items-end justify-between gap-4"><div><p className="eyebrow">{query ? 'Search results' : favoriteTools.length ? 'Favorites' : 'Continue working'}</p><h2 className="mt-2 text-xl font-semibold tracking-tight text-white">{query ? `${results.length} matching tools` : 'Ready when you are'}</h2></div><button onClick={() => router.push('/dashboard/category/formatting')} className="inline-flex items-center gap-1 text-sm font-medium text-violet-200 transition hover:text-white">View all tools <ArrowRight className="size-4" /></button></div><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{shownTools.map((tool, index) => <button key={tool.slug} onClick={() => router.push(`/dashboard/tools/${tool.slug}`)} className="app-panel-interactive group min-h-40 p-5 text-left"><span className={`grid size-9 place-items-center rounded-xl ${index % 3 === 1 ? 'bg-teal-300/15 text-teal-200' : 'bg-violet-300/15 text-violet-200'}`}><Blocks className="size-4" /></span><div className="mt-7 flex items-start justify-between gap-3"><div><b className="block text-sm font-medium text-zinc-100">{tool.name}</b><p className="mt-1 line-clamp-2 text-xs leading-5 text-zinc-500">{tool.description}</p></div><ArrowRight className="mt-0.5 size-4 shrink-0 text-zinc-600 transition group-hover:translate-x-0.5 group-hover:text-violet-200" /></div></button>)}{shownTools.length === 0 && <p className="col-span-full rounded-xl border border-dashed border-white/10 p-8 text-center text-sm text-zinc-500">No tools match your search.</p>}</div></section>

    <div className="mt-10 grid gap-6 lg:grid-cols-[1.35fr_.65fr]"><section className="app-panel p-5 sm:p-6"><div className="flex items-center justify-between"><div><p className="eyebrow">Browse by domain</p><h2 className="mt-1 text-lg font-semibold text-white">A tool for every small task</h2></div><Sparkles className="size-5 text-violet-200" /></div><div className="mt-5 grid grid-cols-2 gap-2 sm:grid-cols-4">{categories.slice(0, 8).map((category) => <button key={category.id} onClick={() => router.push(`/dashboard/category/${category.id}`)} className="rounded-xl border border-white/[.07] bg-white/[.025] p-3 text-left text-xs text-zinc-400 transition hover:border-white/[.14] hover:bg-white/[.06] hover:text-zinc-100"><span className="line-clamp-2">{category.name}</span></button>)}</div></section><section className="app-panel p-5 sm:p-6"><div className="flex items-center gap-2"><Clock3 className="size-4 text-teal-200" /><div><p className="eyebrow">Activity</p><h2 className="mt-1 text-lg font-semibold text-white">Recently used</h2></div></div><div className="mt-5 space-y-3">{recentTools.length ? recentTools.map((tool) => <button key={tool.slug} onClick={() => router.push(`/dashboard/tools/${tool.slug}`)} className="flex w-full items-center gap-3 rounded-xl p-2 text-left transition hover:bg-white/[.05]"><span className="grid size-8 place-items-center rounded-lg bg-white/[.06] text-zinc-400"><Star className="size-3.5" /></span><span className="min-w-0"><b className="block truncate text-xs font-medium text-zinc-200">{tool.name}</b><small className="text-[11px] text-zinc-600">Open tool</small></span></button>) : <p className="py-4 text-sm leading-6 text-zinc-500">Your activity will appear here after you use a tool.</p>}</div></section></div>
  </div>;
}
