import { describe, it, expect } from 'vitest';
import {
  generateGitHookOutput,
  generateHookInstallCommands,
  validateHuskyConfig,
  HUSKY_PRESETS,
} from '@/lib/husky-utils';

describe('Git Hook Builder Utilities (husky-utils.ts)', () => {
  it('should generate valid Husky v9 shell script output', () => {
    const preset = HUSKY_PRESETS[0].config;
    const script = generateGitHookOutput(preset);

    expect(script).toContain('#!/usr/bin/env sh');
    expect(script).toContain('. "$(dirname -- "$0")/_/husky.sh"');
    expect(script).toContain('npx lint-staged');
    expect(script).toContain('pnpm test && pnpm type-check');
  });

  it('should generate valid Lefthook YAML workflow output', () => {
    const preset = HUSKY_PRESETS[1].config;
    const yaml = generateGitHookOutput(preset);

    expect(yaml).toContain('# lefthook.yml generated by DevForge');
    expect(yaml).toContain('pre-commit:');
    expect(yaml).toContain('commands:');
    expect(yaml).toContain('run: pnpm lint');
  });

  it('should generate correct install command for pnpm and husky', () => {
    const cmd = generateHookInstallCommands(HUSKY_PRESETS[0].config);
    expect(cmd).toContain('husky init');
  });

  it('should detect when no hooks are enabled', () => {
    const res = validateHuskyConfig({
      runner: 'husky-v9',
      packageManager: 'npm',
      hooks: [
        {
          id: '1',
          hookType: 'pre-commit',
          command: 'npm test',
          enabled: false,
        },
      ],
    });

    expect(res.isValid).toBe(false);
    expect(res.errors[0]).toContain('At least one hook rule must be enabled');
  });
});
